# Generated by Django 5.2.6 on 2025-09-11 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='record',
            name='artist',
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main_app.record'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.ManyToManyField(related_name='records', to='main_app.artist'),
        ),
    ]
