# Generated by Django 5.2.6 on 2025-09-11 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_artist_name_remove_record_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='artist',
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.record'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
